Migration to flutter_web_auth_2
teranetsrl/oauth2_client pull request #139
Opened 2022-09-08 06:14 UTC by PiotrMitkowski

Migrating to a new fork of abandoned `flutter_web_auth` package.

Fixes #137

2022-09-08 06:33 UTC, PiotrMitkowski commented
@okrad @ThexXTURBOXx do you mind taking a look at my changes to confirm, that they're fine?

2022-09-08 06:40 UTC, ThexXTURBOXx requested changes
As said in one of the comments, do you mind searching (via IDE, for example) for every occurrence of `flutter_web_auth` or `FlutterWebAuth` or similar to confirm there is not another occurrence that was forgotten?

2022-09-08 06:40 UTC, ThexXTURBOXx commented on CHANGELOG.md
> +## [2.5.0] - 2022/09/08
Maybe a major version change might be appropriate since `flutter_web_auth_2` does not support Flutter < 3 anymore? @okrad

2022-09-08 06:40 UTC, ThexXTURBOXx commented on README.md
> -<activity android:name="com.linusu.flutter_web_auth.CallbackActivity" android:exported="true">
A few lines above this, you ought want to change the string to `flutter_web_auth_2` again. In fact, an overall search for `flutter_web_auth` in the entire project might be appropriate.

2022-09-08 06:40 UTC, ThexXTURBOXx commented on README.md
> -<activity android:name="com.linusu.flutter_web_auth.CallbackActivity" android:exported="true">
Also a few lines above this one

2022-09-08 06:41 UTC, ThexXTURBOXx commented
Also, I will be home in around 2-3 hours and can search for more occurrences myself. Just give me time until then and we will be fine afterwards :)

2022-09-08 08:14 UTC, PiotrMitkowski commented
@ThexXTURBOXx Updated the code after doing an overall search in project, as you've suggested. You can take a second look to make sure, that I haven't missed anything :)

I'll wait for @okrad confirmation for the versioning.

2022-09-08 10:38 UTC, ThexXTURBOXx commented
@PiotrMitkowski I have made many additional updates in https://github.com/PiotrMitkowski/oauth2_client/pull/1. Please take a look at that one.
There are many style changes due to the migration away from `pedantic` to `flutter_lints` (since `pedantic` was deprecated quite some time ago).
I thought, these changes might be very convenient to apply right now as we are facing a major version change anyways.
@okrad and @PiotrMitkowski could you maybe take a look at [this PR](https://github.com/PiotrMitkowski/oauth2_client/pull/1)?

2022-09-11 09:25 UTC, okrad commented
@PiotrMitkowski, @ThexXTURBOXx thank you for your work!

The PR by @PiotrMitkowski looks good. The tests are passing so I guess I might as well merge it right away, but I prefer to do some more manual tests just in case.
Moreover I think I'll add some sort of alert in the README to stress out the fact that flutter must be upgraded to v3.

As for @ThexXTURBOXx PR, that's quite a huge PR, and as such I need to take the time to review it, but I agree these changes should be shipped in the 3.0.0 version, since they introduce more breaking changes (i.e. camelcase constant names).

2022-09-11 09:33 UTC, ThexXTURBOXx commented
@okrad Sounds good! If you want, you can merge this PR right away and I will open a new PR directly here in this repo. Maybe that's better for you to have a better overview of everything.
There are not too many changes, except for dependency updates and applying the new linting rules, so I would not expect any new bugs.
The tests at least are still passing.

2022-09-11 11:14 UTC, okrad commented
@ThexXTURBOXx, that'll be nice, thank you!

2022-09-13 17:10 UTC, ThexXTURBOXx commented
@okrad Perfect, thank you very much! I will open my PR in approximately an hour!

2022-09-13 21:21 UTC, ThexXTURBOXx commented
See my new PR in #141 btw :)

2022-09-15 07:32 UTC, PiotrMitkowski commented
I'll close this PR since it's been merged to the dev branch :)

2022-09-15 07:32 UTC, closed without merging